languageCode = 'en-us'
title = 'Reference documentation for JSON Schema'
staticDir = [ './vendor/bootstrap-icons/font/fonts', './static' ]
paginate = 100000000

[Params]
description = 'Reference documentation for JSON Schema'
github = 'https://github.com/1mrekq/metafora-jsonschema'
slack = 'https://json-schema.org/slack'
jsonschema = 'https://json-schema.org'
frameworkName = 'Metafora'

[markup]
  [markup.highlight]
    lineNos = false
    noClasses = false
